SawLuz/Models/Restaurante.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SawLuz.Models
{
    public class Restaurante
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }

        //[Display(Name ="Prato")]
        //public int IdPrato { get; set; }
        //public virtual Prato Prato { get; set; }

        public List<Prato> Pratos { get; set; }
    }
}

SawLuz/Controllers/RestauranteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SawLuz.Models;

namespace SawLuz.Controllers
{
    public class RestauranteController : Controller
    {
        private Contexto db = new Contexto();

        //// GET: Restaurante/Pesquisa/5
        //public ActionResult Pesquisa(string nome)
        //{
        //    var listaPesquisa = db.Restaurantes.Where(x => x.Nome == nome);
        //    return View(listaPesquisa.ToList());
        //}

        // GET: Restaurante
        public ActionResult Index(string pesquisa = "")
        {
            var query = db.Restaurantes.AsQueryable();
            if (!string.IsNullOrEmpty(pesquisa))
            {
                query = query.Where(x => x.Nome.Contains(pesquisa));
                query = query.OrderBy(x => x.Nome);
            }

            return View(query.ToList());
        }

        // GET: Restaurante/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurante restaurante = db.Restaurantes.Find(id);
            if (restaurante == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        // GET: Restaurante/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurante/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,IdPrato")] Restaurante restaurante)
        {
            if (ModelState.IsValid)
            {
                db.Restaurantes.Add(restaurante);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurante);
        }

        // GET: Restaurante/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurante restaurante = db.Restaurantes.Find(id);
            if (restaurante == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        // POST: Restaurante/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,IdPrato")] Restaurante restaurante)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurante).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurante);
        }

        // GET: Restaurante/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurante restaurante = db.Restaurantes.Find(id);
            if (restaurante == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        // POST: Restaurante/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurante restaurante = db.Restaurantes.Find(id);
            db.Restaurantes.Remove(restaurante);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SawLuz/Views/Restaurante/Create.cshtml
@model SawLuz.Models.Restaurante

@{
    ViewBag.Title = "Novo Restaurante";
}

<h2>Cadastro de Restaurante</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurante</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Restaurante")">
                    <div class="btn btn-danger"> Cancelar </div>
                </a>
            </div>
            
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SawLuz/Views/Restaurante/Delete.cshtml
@model SawLuz.Models.Restaurante

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir Restaurante</h2>

<h3>Deseja realmente excluir este Restaurante?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" /> 
            <a href="@Url.Action("Index", "Restaurante")">
                <div class="btn btn-primary"> Cancelar </div>
            </a>
        </div>
    }
</div>

SawLuz/Views/Restaurante/Details.cshtml
@model SawLuz.Models.Restaurante

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Restaurante</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdPrato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPrato)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SawLuz/Views/Restaurante/Edit.cshtml
@model SawLuz.Models.Restaurante

@{
    ViewBag.Title = "Alterar Restaurante";
}

<h2>Alterar Dados do Restaurante</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurante</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Alterar" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Restaurante")">
                    <div class="btn btn-danger"> Cancelar </div>
                </a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SawLuz/Views/Restaurante/Index.cshtml
@model IEnumerable<SawLuz.Models.Restaurante>

@{
    ViewBag.Title = "Index";
}

<h2>Restaurantes</h2>



<div class="form-group-lg">
    @using (@Html.BeginForm())
    {
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-10">
                    Pesquisa por Nome:

                    @Html.TextBox("Pesquisa")
                </div>
                </div>
            <div class="form-group">
                <div class="col-md-10">
                    <a href="@Url.Action("Create", "Restaurante")">
                        <div class="btn btn-primary"> Cadastrar Novo Restaurante </div>
                    </a>
                    <input type="submit" value="Pesquisar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>

        <td>
            @Html.ActionLink("Alterar", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Excluir", "Delete", new { id = item.Id })
        </td>

    </tr>
    }

</table>