SawLuz/Models/Prato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SawLuz.Models
{
    public class Prato
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        [Display(Name ="Valor (R$)")]
        [DisplayFormat(DataFormatString = "{0:n2}")]
        public double Valor { get; set; }

        //public List<Restaurante> Restaurantes { get; set; }

        [Display(Name ="Restaurante")]
        public int RestauranteId { get; set; }
        public virtual Restaurante Restaurante { get; set; }
    }
}

SawLuz/Controllers/PratoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SawLuz.Models;

namespace SawLuz.Controllers
{
    public class PratoController : Controller
    {
        private Contexto db = new Contexto();

        // GET: Prato
        public ActionResult Index()
        {
            var pratos = db.Pratos.Include(x => x.Restaurante);
            
            ViewBag.RestauranteId = new SelectList(db.Restaurantes, "Id", "Nome");

            //return View(db.Pratos.Include(t => t.Restaurante).ToList());
            return View(db.Pratos.ToList());
           // return View(pratos);
        }

        // GET: Prato/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prato prato = db.Pratos.Find(id);
            if (prato == null)
            {
                return HttpNotFound();
            }
            return View(prato);
        }

        // GET: Prato/Create
        public ActionResult Create()
        {
            ViewBag.RestauranteId = new SelectList(db.Restaurantes, "Id", "Nome");

            return View();
        }

        // POST: Prato/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Valor,RestauranteId")] Prato prato)
        {
            if (ModelState.IsValid)
            {
                
                db.Pratos.Add(prato);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RestauranteId = new SelectList(db.Restaurantes, "Id", "Nome");

            return View(prato);
        }

        // GET: Prato/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prato prato = db.Pratos.Find(id);
            if (prato == null)
            {
                return HttpNotFound();
            }

            ViewBag.RestauranteId = new SelectList(db.Restaurantes, "Id", "Nome");
            return View(prato);
        }

        // POST: Prato/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Valor,RestauranteId")] Prato prato)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prato).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RestauranteId = new SelectList(db.Restaurantes, "Id", "Nome");
            return View(prato);
        }

        // GET: Prato/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prato prato = db.Pratos.Find(id);
            if (prato == null)
            {
                return HttpNotFound();
            }
            return View(prato);
        }

        // POST: Prato/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prato prato = db.Pratos.Find(id);
            db.Pratos.Remove(prato);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SawLuz/Views/Prato/Create.cshtml
@model SawLuz.Models.Prato

@{
    ViewBag.Title = "Cadastro de Prato";
}

<h2>Cadastro de Prato</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">

            @Html.LabelFor(model => model.RestauranteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RestauranteId, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RestauranteId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Prato")">
                    <div class="btn btn-danger"> Cancelar </div>
                </a>
            </div>

        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SawLuz/Views/Prato/Delete.cshtml
@model SawLuz.Models.Prato

@{
    ViewBag.Title = "Excluir Prato";
}

<h2>Excluir Prato</h2>

<h3>Deseja realmente excluir este Prato?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" /> 
            <a href="@Url.Action("Index", "Prato")">
                <div class="btn btn-primary"> Cancelar </div>
            </a>
        </div>
    }
</div>

SawLuz/Views/Prato/Details.cshtml
@model SawLuz.Models.Prato

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Prato</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SawLuz/Views/Prato/Edit.cshtml
@model SawLuz.Models.Prato

@{
    ViewBag.Title = "Edit";
}

<h2>ALterar Dados do Prato</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">

            @Html.LabelFor(model => model.RestauranteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RestauranteId, null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RestauranteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Prato")">
                    <div class="btn btn-danger"> Cancelar </div>
                </a>
            </div>

        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SawLuz/Views/Prato/Index.cshtml
@model IEnumerable<SawLuz.Models.Prato>

@{
    ViewBag.Title = "Pratos";
}

<h2>Pratos</h2>

<div class="form-group">
    <a href="@Url.Action("Create","Prato")">
        <div class="btn btn-primary">
            Cadastrar Novo Prato
        </div>
    </a>    
</div>

<div class="form-group">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RestauranteId)
            </th>
            <th>
                @Html.DisplayName("Prato")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>                 
               
                    @Html.DisplayFor(modelItem => item.Restaurante.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>

                <td>
                    @Html.ActionLink("Alterar", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
</div>